#!/bin/bash
#this script creates a simple archival information package in which the data objects are placed into a directory called video files and the metadata files (or whatever they are called in OAIS) are placed into a directory called metadata, and both of these directories are stored in a directory based on the file name of the input file. 
_writemetadata(){
    DESCRIPTIVE="${METADATAFILES}/description.txt"
    if [ ! -f "${DESCRIPTIVE}" ] ; then
        touch "${DESCRIPTIVE}"
    fi
    KEY="${1}"
    VALUE="${2}"
    # need to add yaml style escaping
    echo "${KEY}: ${VALUE}" >> "${DESCRIPTIVE}"
}

while [ "${*}" != "" ] ; do
    INPUT="${1}"
    shift
	
	#ask questions about the input to create a short descriptive metadata text file
	cowsay -s "Rename the file with a simple unique identifier"
	echo -n ":: "
	read MEDIAID
	
	cowsay -s "Who is the creator of this file?"
	echo -n ":: "
	read CREATOR

	cowsay -s "When was this file created?"
	echo -n ":: "
	read DATECREATED

	cowsay -s "Provide a short description of the file."
	echo -n ":: "
	read DESCRIPTION
    
    #set up the directory structure of the package 
	PACKAGE="$HOME/Desktop/${MEDIAID}/"
    mkdir -p "${PACKAGE}"
    echo "${PACKAGE}"
	METADATAFILES="${PACKAGE}/metadata/"
    mkdir -p "${METADATAFILES}"
    echo "${METADATAFILES}"
	VIDEOFILES="${PACKAGE}/videofiles/"
    mkdir -p "${VIDEOFILES}"
    echo "${VIDEOFILES}"
	
	#write results to a file
	_writemetadata "Creator" "${CREATOR}"
	_writemetadata "Date Created" "${DATECREATED}" 
	_writemetadata "Description" "${DESCRIPTION}"
    
	#encode an access copy with the file name as the media id and add an _access
    OUTPUT="${MEDIAID}_access.mov"
	ffmpeg -i "${INPUT}" -c:v libx264 -pix_fmt yuv420p -preset veryslow -crf 18 -c:a copy "${OUTPUT}"
	
	#create mediainfo.xml file with technical metadata in metadata directory
	#if you have this data in a structured format, it will be easier to input it into a spreadsheet if you ever do get software
	MEDIAINFOXML1="${METADATAFILES}/${INPUT}_mediainfo.xml"
    mediaconch -mi -fx "${INPUT}" | xml fo > "${MEDIAINFOXML1}"
	MEDIAINFOXML2="${METADATAFILES}/${OUTPUT}_mediainfo.xml"
    mediaconch -mi -fx "${OUTPUT}" | xml fo > "${MEDIAINFOXML2}"
    
    
	
	#move the preservation master and access copy into the videofiles directory 
	mv -v -n "${INPUT}" "${VIDEOFILES}"
    mv -v -n "${OUTPUT}" "${VIDEOFILES}"
	
	#create checksums for files in the videofiles directory 
	cd "${VIDEOFILES}"
	echo "Creating checksums for the video files..."
	md5deep -drl . > "${METADATAFILES}/checksum.md5"
	
	#report that the script has completed processing media id 
	echo "The processing of package ${MEDIAID} is complete."

done